#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace TeamNexgen.Data	
{
	public partial class Connection
	{
		private int _connectionId;
		public virtual int ConnectionId
		{
			get
			{
				return this._connectionId;
			}
			set
			{
				this._connectionId = value;
			}
		}
		
		private int _userId;
		public virtual int UserId
		{
			get
			{
				return this._userId;
			}
			set
			{
				this._userId = value;
			}
		}
		
		private string _server;
		public virtual string Server
		{
			get
			{
				return this._server;
			}
			set
			{
				this._server = value;
			}
		}
		
		private int _port;
		public virtual int Port
		{
			get
			{
				return this._port;
			}
			set
			{
				this._port = value;
			}
		}
		
		private bool _connected;
		public virtual bool Connected
		{
			get
			{
				return this._connected;
			}
			set
			{
				this._connected = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private bool _monitoring;
		public virtual bool Monitoring
		{
			get
			{
				return this._monitoring;
			}
			set
			{
				this._monitoring = value;
			}
		}
		
		private int _serviceTypeId;
		public virtual int ServiceTypeId
		{
			get
			{
				return this._serviceTypeId;
			}
			set
			{
				this._serviceTypeId = value;
			}
		}
		
	}
}
#pragma warning restore 1591
