#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace TeamNexgen.Data	
{
	public partial class ServiceType
	{
		private int _serviceTypeId;
		public virtual int ServiceTypeId
		{
			get
			{
				return this._serviceTypeId;
			}
			set
			{
				this._serviceTypeId = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private byte _isActive;
		public virtual byte IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		
		private int _serviceType1;
		public virtual int ServiceType1
		{
			get
			{
				return this._serviceType1;
			}
			set
			{
				this._serviceType1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
