#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace TeamNexgen.Data	
{
	public partial class User
	{
		private int _userId;
		public virtual int UserId
		{
			get
			{
				return this._userId;
			}
			set
			{
				this._userId = value;
			}
		}
		
		private string _emailAddress;
		public virtual string EmailAddress
		{
			get
			{
				return this._emailAddress;
			}
			set
			{
				this._emailAddress = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private string _ircUser;
		public virtual string IrcUser
		{
			get
			{
				return this._ircUser;
			}
			set
			{
				this._ircUser = value;
			}
		}
		
		private string _ircServerName;
		public virtual string IrcServerName
		{
			get
			{
				return this._ircServerName;
			}
			set
			{
				this._ircServerName = value;
			}
		}
		
		private string _ircRealName;
		public virtual string IrcRealName
		{
			get
			{
				return this._ircRealName;
			}
			set
			{
				this._ircRealName = value;
			}
		}
		
		private string _ircHostName;
		public virtual string IrcHostName
		{
			get
			{
				return this._ircHostName;
			}
			set
			{
				this._ircHostName = value;
			}
		}
		
		private string _nickname;
		public virtual string Nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				this._nickname = value;
			}
		}
		
		private bool _emailVerified;
		public virtual bool EmailVerified
		{
			get
			{
				return this._emailVerified;
			}
			set
			{
				this._emailVerified = value;
			}
		}
		
		private string _registrationGuid;
		public virtual string RegistrationGuid
		{
			get
			{
				return this._registrationGuid;
			}
			set
			{
				this._registrationGuid = value;
			}
		}
		
	}
}
#pragma warning restore 1591
